rethinkdb:
    image: rethinkdb
    ports:
        - "8080"
        - "28015"
        - "29015"
proxy:
    image: ehazlett/docker-proxy:latest
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
        - "2375"
    command: -D

swarm:
    image: swarm:latest
    command: m --host tcp://0.0.0.0:2375 proxy:2375
    links:
        - "proxy:proxy"
    ports:
        - "2375"

media:
    build: .
    entrypoint: /bin/bash
    dockerfile: Dockerfile.build
    command: -c "make media && sleep infinity"
    working_dir: /go/src/github.com/shipyard/shipyard
    volumes:
        - "/go/src/github.com/shipyard/shipyard/controller/static"
    environment:
        - no_proxy=0.0.0.0,swarm,rethinkdb,media,proxy,authproxy,registry
        - NO_PROXY=0.0.0.0,swarm,rethinkdb,media,proxy,authproxy,registry

registry:
    image: registry:0.8.1
    volumes:
      - /var/registry:/registry
    ports:
      - "80:5000"
    environment:
      - "SETTINGS_FLAVOR=local"
      - "SEARCH_BACKEND=sqlalchemy"
      - "STORAGE_PATH=/registry"

authproxy:
    image: quay.io/aptible/registry-proxy
    links:
      - registry
    ports:
      - "443:443"
    environment:
      - AUTH_CREDENTIALS=admin:admin
    volumes:
      - ./registry-assets/external:/etc/nginx/ssl

controller:
    build: .
    dockerfile: Dockerfile.build
    entrypoint: /bin/bash
    command: -c "make build && cd controller && ./controller -D server --rethinkdb-addr rethinkdb:28015 -d tcp://swarm:2375"
    links:
        - rethinkdb
        - swarm
        - authproxy
        - registry
    volumes_from:
        - media
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
        - "8080:8080"
    environment:
        - no_proxy=0.0.0.0,swarm,rethinkdb,media,proxy,authproxy,registry
        - NO_PROXY=0.0.0.0,swarm,rethinkdb,media,proxy,authproxy,registry
