controller:
    command: -c "make build && godep go test -v ./controller"
    links:
        - rethinkdb
        - swarm
    volumes:
        - .:/go/src/github.com/shipyard/shipyard
    volumes_from:
        - media
